import { Stack, StackProps, CfnOutput } from "aws-cdk-lib";
import { Construct } from "constructs";
import * as iam from "aws-cdk-lib/aws-iam";
import {
  GITHUB_OIDC_AUDIENCE,
  GITHUB_OIDC_AUD_CONDITION_KEY,
  GITHUB_OIDC_ISSUER_URL,
  GITHUB_OIDC_SUB_CONDITION_KEY,
} from "./github-oidc";

export interface SchemaInfraOidcStackProps extends StackProps {
  // Owner/repo string GitHub embeds in OIDC `sub` claims. e.g.
  // "EdgeVector/schema-infra".
  githubRepo: string;
}

// Account-global IAM resources that let GitHub Actions in
// `EdgeVector/schema-infra` deploy to AWS via OIDC instead of long-lived
// static access keys. Deployed once (us-east-1 is fine — IAM is global)
// before the workflow flips to OIDC; not deployed by deploy.yml itself.
//
// Two roles, scoped via OIDC `sub` claim:
//   SchemaInfraDeployDev  — refs/heads/main only (tightened from any ref),
//                           us-west-2 CDK bootstrap roles plus the
//                           SchemaServiceStack-dev pipeline actions.
//   SchemaInfraDeployProd — refs/heads/main only, us-east-1 CDK bootstrap
//                           roles plus the SchemaServiceStack-prod pipeline
//                           actions.
//
// Both roles also carry the resource-scoped actions that the staged deploy
// pipeline (.lastgit/deploy-pipeline.sh) calls through the AWS CLI. The
// GitHub deploy workflow must NOT use a GitHub `environment:` key: it changes
// the OIDC `sub` claim to `environment:<name>`, and these trusts match the
// ref-based claim only.
export class SchemaInfraOidcStack extends Stack {
  constructor(scope: Construct, id: string, props: SchemaInfraOidcStackProps) {
    super(scope, id, props);

    // Issuer URL and audience live in ./github-oidc.ts, the same literals the
    // trust-policy condition keys below are built from.
    const provider = new iam.OpenIdConnectProvider(this, "GitHubOidcProvider", {
      url: GITHUB_OIDC_ISSUER_URL,
      clientIds: [GITHUB_OIDC_AUDIENCE],
    });

    const account = Stack.of(this).account;
    const cdkBootstrapRoleArns = (region: string) => [
      `arn:aws:iam::${account}:role/cdk-hnb659fds-deploy-role-${account}-${region}`,
      `arn:aws:iam::${account}:role/cdk-hnb659fds-file-publishing-role-${account}-${region}`,
      `arn:aws:iam::${account}:role/cdk-hnb659fds-image-publishing-role-${account}-${region}`,
      `arn:aws:iam::${account}:role/cdk-hnb659fds-lookup-role-${account}-${region}`,
    ];

    const buildRole = (
      roleId: string,
      roleName: string,
      subCondition: { test: "StringEquals" | "StringLike"; value: string },
      region: string,
      stackName: string,
      envName: "dev" | "prod",
    ): iam.Role => {
      const conditions: Record<string, Record<string, string>> = {
        StringEquals: {
          [GITHUB_OIDC_AUD_CONDITION_KEY]: GITHUB_OIDC_AUDIENCE,
        },
      };
      conditions[subCondition.test] = {
        ...(conditions[subCondition.test] ?? {}),
        [GITHUB_OIDC_SUB_CONDITION_KEY]: subCondition.value,
      };

      const role = new iam.Role(this, roleId, {
        roleName,
        assumedBy: new iam.FederatedPrincipal(
          provider.openIdConnectProviderArn,
          conditions,
          "sts:AssumeRoleWithWebIdentity",
        ),
        description: `GitHub Actions OIDC role for ${props.githubRepo} (${region})`,
      });

      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "AssumeCdkBootstrapRoles",
          actions: ["sts:AssumeRole"],
          resources: cdkBootstrapRoleArns(region),
        }),
      );

      // The deploy workflow's post-deploy step calls `aws cloudformation
      // describe-stacks` directly (not through cdk), so the OIDC role
      // itself needs that permission scoped to the relevant stack.
      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "ReadStackOutputs",
          actions: ["cloudformation:DescribeStacks"],
          resources: [
            `arn:aws:cloudformation:${region}:${account}:stack/${stackName}/*`,
          ],
        }),
      );

      // Staged-deploy pipeline actions (code-publish.sh, canary-lib.sh,
      // smoke-dev.sh, prove-mutation-gate.sh). The Lambda function name is
      // generated by CDK as `<stack name>-<logical id><hash>`, so the stack
      // name prefix is the narrowest stable scope.
      const fnPrefix = `SchemaServiceStack-${envName}-`;
      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "SchemaLambdaCodeAliasVersion",
          actions: [
            "lambda:UpdateFunctionCode",
            "lambda:PublishVersion",
            "lambda:UpdateAlias",
            "lambda:GetAlias",
            "lambda:GetFunction",
            "lambda:GetFunctionConfiguration",
            "lambda:GetProvisionedConcurrencyConfig",
            "lambda:PutProvisionedConcurrencyConfig",
            "lambda:DeleteProvisionedConcurrencyConfig",
          ],
          resources: [
            `arn:aws:lambda:${region}:${account}:function:${fnPrefix}*`,
            `arn:aws:lambda:${region}:${account}:function:${fnPrefix}*:*`,
          ],
        }),
      );
      // DescribeAlarms does not support resource-level scoping; it is
      // read-only and used by the canary alarm gate.
      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "ReadCanaryAlarms",
          actions: ["cloudwatch:DescribeAlarms"],
          resources: ["*"],
        }),
      );
      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "ReadSchemaLambdaLogs",
          actions: ["logs:FilterLogEvents"],
          resources: [
            `arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${fnPrefix}*`,
            `arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${fnPrefix}*:*`,
          ],
        }),
      );
      // Mutation-gate smoke reads the quota table (Scan --select COUNT).
      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "SmokeReadQuotaTable",
          actions: [
            "dynamodb:Scan",
            "dynamodb:Query",
            "dynamodb:GetItem",
            "dynamodb:DescribeTable",
          ],
          resources: [
            `arn:aws:dynamodb:${region}:${account}:table/schema-mutation-gate-quotas-${envName}`,
          ],
        }),
      );
      // Artifact bucket: the CDK bootstrap staging bucket for this region.
      role.addToPolicy(
        new iam.PolicyStatement({
          sid: "ArtifactBucketAccess",
          actions: ["s3:GetObject", "s3:PutObject", "s3:ListBucket"],
          resources: [
            `arn:aws:s3:::cdk-hnb659fds-assets-${account}-${region}`,
            `arn:aws:s3:::cdk-hnb659fds-assets-${account}-${region}/*`,
          ],
        }),
      );

      return role;
    };

    const devRole = buildRole(
      "DeployDevRole",
      "SchemaInfraDeployDev",
      // Dev is locked to main. It used to trust `repo:<repo>:*`, which let
      // any ref and any pull_request run assume the role. The deploy
      // workflow runs from main (workflow_run of ci-required, or a manual
      // dispatch on main), so the ref-based claim is enough.
      {
        test: "StringEquals",
        value: `repo:${props.githubRepo}:ref:refs/heads/main`,
      },
      "us-west-2",
      "SchemaServiceStack-dev",
      "dev",
    );

    const prodRole = buildRole(
      "DeployProdRole",
      "SchemaInfraDeployProd",
      // Prod is locked to main. deploy.yml's `if: github.ref ==
      // 'refs/heads/main'` is belt; this OIDC condition is suspenders —
      // a future workflow edit that removed the gate still couldn't
      // assume this role from a feature branch.
      {
        test: "StringEquals",
        value: `repo:${props.githubRepo}:ref:refs/heads/main`,
      },
      "us-east-1",
      "SchemaServiceStack-prod",
      "prod",
    );

    new CfnOutput(this, "DeployDevRoleArn", {
      value: devRole.roleArn,
      description: "ARN to wire into deploy.yml's deploy-dev job (role-to-assume)",
    });
    new CfnOutput(this, "DeployProdRoleArn", {
      value: prodRole.roleArn,
      description: "ARN to wire into deploy.yml's deploy-prod job (role-to-assume)",
    });
    new CfnOutput(this, "GitHubOidcProviderArn", {
      value: provider.openIdConnectProviderArn,
      description: "Account-wide GitHub Actions OIDC provider ARN",
    });
  }
}
